name: Update Blog Metadata

on:
  push:
    paths:
      - "blogs/**/*.md"  # Trigger the workflow when markdown files in the posts directory are pushed

jobs:
  update_metadata:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2  # Ensure we have enough history to detect changes
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-frontmatter

      - name: Run metadata update script
        run: |
          python metadataWorkflow.py

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add metadata.json
          git commit -m "Update blog metadata"
          git push
